import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    // Everything stays autogenerated at root level
    {
      type: 'autogenerated',
      dirName: '.',
    },
    {
      type: 'link',
      label: 'Litepaper',
      href: 'https://liberdus.com/Liberdus-Litepaper.pdf',
    },
  ],
};

export default sidebars;
